export const OrderDetailsDataConst = [
  {
    id: 0,
    itemsName: [
      { item: 'Veg pizza', cost: '150' },
      { item: 'Non-veg pizza', cost: '150' },
      { item: 'Garlic Bread', cost: '100' },
      { item: 'Cold drink', cost: '63' },
    ],
    customerName: 'Alex',
    totalAmmountOfOrder: 'Rs 463/',
    address: '311 b block',
  },
  {
    id: 1,
    customerName: 'Carry',
    totalAmmountOfOrder: 'Rs 43/',
    itemsName: [{ item: 'Cold drink', cost: '43' }],
    address: '311 b block',
  },
  {
    id: 2,
    customerName: 'Steven',
    totalAmmountOfOrder: 'Rs 963/',
    itemsName: [
      { item: 'Veg pizza', cost: '150' },
      { item: 'Non-veg pizza', cost: '150' },
      { item: 'Garlic Bread', cost: '100' },
      { item: 'Garlic Bread', cost: '100' },
      { item: 'Garlic Bread', cost: '100' },
      { item: 'Garlic Bread', cost: '300' },
      { item: 'Cold drink', cost: '63' },
    ],
    address: '311 b block',
  },
  {
    id: 3,
    customerName: 'Smith',
    itemsName: [
      { item: 'Veg pizza', cost: '100' },
      { item: 'Non-veg pizza', cost: '100' },
      { item: 'Garlic Bread', cost: '100' },
      { item: 'Cold drink', cost: '63' },
    ],
    address: '311 b block',
    totalAmmountOfOrder: 'Rs 363/',
  },
  {
    id: 5,
    customerName: 'Glenn',
    itemsName: [
      { item: 'Veg pizza', cost: '150' },
      { item: 'Non-veg pizza', cost: '150' },
      { item: 'Garlic Bread', cost: '100' },
      { item: 'Garlic Bread', cost: '100' },
      { item: 'Garlic Bread', cost: '100' },
      { item: 'Garlic Bread', cost: '100' },
      { item: 'Garlic Bread', cost: '100' },
      { item: 'Garlic Bread', cost: '100' },
      { item: 'Garlic Bread', cost: '100' },
      { item: 'Garlic Bread', cost: '100' },
      { item: 'Garlic Bread', cost: '100' },
      { item: 'Garlic Bread', cost: '100' },
      { item: 'Garlic Bread', cost: '100' },
      { item: 'Cold drink', cost: '63' },
    ],
    address: '311 b block',
    totalAmmountOfOrder: 'Rs 1463/',
  },
];
